# config.yml

# Параметры обучения
train:
  batch_size: 16
  epochs: 20
  learning_rate: 0.0001
  dropout_rate: 0.15
  optimizer: adam
  n_hidden: 1024

# Параметры данных
data:
  train_csv: train.csv
  dev_csv: dev.csv
  test_csv: test.csv
  augmentation:
    noise: False
    speed: False
    pitch: False

# Параметры модели
model:
  type: DeepSpeech
  alphabet_config_path: alphabet.txt
  scorer_path: scorer.scorer
